# Generated by Django 4.0 on 2021-12-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTradesman',
            fields=[
                ('bt_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(upload_to=True)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=10)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('created_time', models.DateTimeField(blank=True)),
                ('expire_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tradesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_id', models.CharField(max_length=50)),
                ('tradesman_name', models.CharField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField()),
                ('trade_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('token', models.CharField(max_length=255, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tempuser')),
            ],
        ),
    ]
