# Generated by Django 4.0 on 2021-12-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_mobile_customer_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
