# Generated by Django 4.0 on 2021-12-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customer_mobile_number_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
