# Generated by Django 4.0 on 2021-12-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='token',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
