# Generated by Django 4.0 on 2021-12-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customer_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
    ]
