# Generated by Django 4.0 on 2021-12-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_customer_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
    ]
